### ISSUE TITLE
Cannot connect to MeshCentral server on non-standard port

### ISSUE THREAD

**Issue by map7** [Ylianst/MeshCentralAndroidAgent#3]
I'm running my MeshCentral on a none standard port 1025 and when I scan the QR code and click 'connect' the MeshCentralAndroidAgent doesn't connect. It prompts to allow access, but still doesn't connect. I've added a lot of remote computers to my MeshCentral already so I know it can be accessed remotely, just not by the mobile app yet.

I'm using Android 9.0 on a rooted Samsung Galaxy S8.

**Comment by Ylianst** [comment]
Ok, I am working on a new version of the Android Agent and will take a look at this.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.58 with a fix for that. The generated QR code will now work correctly with servers on non-standard ports. I also just published an updated version of the MeshCentral Agent v1.0.2 on Google Play and [APK on download page](https://meshcentral.com/info/downloads.html). However, your issue is with the QR code, so only the server needs to be updated.
